version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
  aws-ecs: circleci/aws-ecs@1.4.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: '${MY_APP_PREFIX}'
          path: ./app
          skip-when-tags-exist: false
          tag: 'latest'
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-task'
          service-name: '${MY_APP_PREFIX}-service'
          cluster-name: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX},tag=latest'
          filters:
            branches:
              only:
                - main
