version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.0

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: pip3 install -r ~/repo/app/requirements.txt

  build-and-push-image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
         account-url: AWS_ACCOUNT_URL
         region: AWS_REGION
         repo: 'flask-app'
         path: ./app

workflows:
  main:
    jobs:
      - build-and-test
      - build-and-push-image:
          requires:
            - build-and-test
